# Generated by Django 5.2.7 on 2025-10-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='text',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
