# Generated by Django 5.2.5 on 2025-08-12 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_alter_pizzamodel_name_alter_pizzamodel_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizzamodel',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelTable(
            name='pizzamodel',
            table='pizzas',
        ),
    ]
